### ISSUE TITLE
Notifier keeps notifying that there are reviews available even if there is none

### ISSUE THREAD

**Issue by chrisjwelly** [wiiaboo/Wanikani-Notifier#2]
I use this add-on on Firefox, and I am not very sure if this is the right place to log an issue since the README file seems to suggest that this is an extension for Chrome. However, the add-on description linked here so I am just going to give it a shot. 

Recently, the Wanikani Notifier started (constantly) telling me that I have 8 reviews available, regardless of whether I have reviews or not. I am not sure what triggered it exactly. I tried to clear my browser cookies, and restarting my device but to no avail. 

Below shows the screenshots of this happening. Note that my notifier is on my upper left-hand corner.
1. The notifier tells me I have 8 reviews
![](https://imgur.com/GYROWhF.png)

2. I clicked on it, only to find that I have actually done all my reviews.
![](https://imgur.com/9k2oAtA.png)

3. A few moments later (an estimate about 10 seconds), I am again notified that I have 8 reviews.
![](https://imgur.com/Paf2zKs.png)

I am currently using Firefox 66.

**Comment by wiiaboo** [comment]
Let me know if this still happens with the latest version.
