### ISSUE TITLE
API v1 is dead

### ISSUE THREAD

**Issue by simonyangme** [wiiaboo/Wanikani-Notifier#3]
The extension has stopped working as the v1 API is now removed.

**Comment by wiiaboo** [comment]
RIP. Only took 3 years.

Can you test it with https://github.com/wiiaboo/Wanikani-Notifier/commit/c09908336f939efa1d15b276cb5a76d4c7d568e2?

If not, I can submit it for AMO for now, and then later with notifications and other stuff I didn't feel like updating.

**Comment by wiiaboo** [comment]
https://addons.mozilla.org/en-US/firefox/addon/wanikani-notifier/
Should be working now with [0.4.93](https://github.com/wiiaboo/Wanikani-Notifier/releases/tag/v0.4.93).
