### ISSUE TITLE
API V2 Key Not Valid

### ISSUE THREAD

**Issue by Koolstr** [wiiaboo/Wanikani-Notifier#5]
Despite now supposedly supporting API V2 keys, it won't accept any of the keys I've generated. It simply returns the error 'API Key is not valid!'. I've tried resetting it as instructed, but that didn't help.

Is this a known issue, and is this being worked on?

**Comment by wiiaboo** [comment]
Can you try and see if the latest version fixes it and if not, please "Wipe All Settings" on the addon's Preferences page. I wasn't too careful about compatibility with older versions of the addon.

**Comment by Koolstr** [comment]
Still not working on the latest version, even after wiping... :/

**Comment by wiiaboo** [comment]
What version and platform of Firefox are you on?

**Comment by Koolstr** [comment]
Firefox v84.0.1, 64-bit, on Windows 10. The problem is the same on my Mac.

**Comment by wiiaboo** [comment]
Can you go to https://www.wanikani.com/settings/personal_access_tokens and use the "Use in Wanikani Notifier" button on any key?

**Comment by Koolstr** [comment]
That worked! Brilliant addition/feature, thank you! This is a good, working extension once again.
API key still reported in the settings as invalid when the save button was clicked, until I did a full wipe and assigned it again using the button. Then clicking the save button says the key was accepted and confirms it by printing my username.
You can close this now if you'd like. Thanks again for attentively addressing this.

**Comment by wiiaboo** [comment]
Cool, and weird that it worked now.
Probably means I need to improve the validation on the options page.
